name: DailyQuote CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
     
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      -  name: Setup Java
         uses: actions/setup-java@v4
         with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle
      - name: Set Up Flutter    
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.24.4
      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.5.4          

      - name: Install Dependencies    
        run: flutter pub get
      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons:main  
      #- name: Test flutter app 
       # run: flutter test
        # build apk
      - name: Build APK
        run: flutter build apk --release

      - name: Build appBundle
        run: flutter build appbundle

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
              
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab"
          tag: v1.0.0
          token: ${{secrets.github_token}}

      #- name: Setup Git
      #  run: |
      #    git config user.name "CI Bot"
      #    git config user.email "ci-bot@example.com"

      #- name: Fetch All Branches
      #  run: git fetch --all

      #- name: Merge Branch
      #  run: |
      #    git checkout main
      #    git merge feature-branch
      #    git push origin main      